- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Build Maven Project
      shell: |
        cd /var/snap/jenkins/5022/workspace/ansiblewebapp-CICD
        mvn clean package

    - name: Copy WAR file to Tomcat
      shell: |
        cp /var/snap/jenkins/5022/workspace/ansiblewebapp-CICD/target/*.war /opt/tomcat/webapps/

    - name: Restart Tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh || true
        sleep 5
        /opt/tomcat/bin/startup.sh
